version: "3.8"

services:
  db:
    image: postgres
    container_name: pg_webflux
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - webflux_data:/var/lib/postgresql/data

volumes:
  webflux_data: